### ISSUE TITLE
Metasmoke is doing things multiple times

### ISSUE THREAD

**Issue by user12986714** [Charcoal-SE/metasmoke#775]
It appears that when performing some actions on metasmoke, it will be automatically repeated for some integer times:
- Create feedback on post: sometimes 2
- Add domain link: always 3
- Auto creation of domain: sometimes 2

This is probably not the intended behaviour of metasmoke.

Related:
https://metasmoke.erwaysoftware.com/data/sql/queries/42-duplicate-domain-tags-405
https://metasmoke.erwaysoftware.com/data/sql/queries/207-duplicate-feedbacks

**Comment by ArtOfCode-** [comment]
This is probably the same old JS bug that's existed forever, probably related to Turbolinks

**Comment by user12986714** [comment]
Looks like this issue is now resolved.

**Comment by makyen** [comment]
The recent change I made to JavaScript event handlers may have reduced the problems, and solved some of them, but it did not resolve all of them. In particular, I can still create multiple feedbacks on the same post.

At least the multiple feedbacks, and some other issues, is the result of a user being permitted to rapidly click twice on the same control. There will be another set of JavaScript changes to resolve that, but I want to make sure the most recent change didn't result in any problems.

**Comment by makyen** [comment]
The feedback issue was addressed in PR #823 and PR #825.

**Comment by tripleee** [comment]
Related? #563

**Comment by makyen** [comment]
Grumble, grumble, multiple things in one issue. :;
